#!/bin/bash

export MAIN_DIR=$PWD
cd ..

require_dir() {
	if [ ! -d "$1" ]; then
		if [ ! -z "$2" ]; then
			echo "Making a dir named '$1'. Location: $MAIN_DIR"
			mkdir "$1"
            sleep 1
		else
			echo "Please run this script with super root to make this dir named $1"
			echo -ne "Or create the directory now? [y/n]: "
			read makedir
		
			if [ "$makedir" != "${makedir#[Yy]}" ]; then
				echo -e "Making a dir named: '$1'"
				mkdir "$1"
			else
				echo -e ""
				echo -e "Cancelled the installasion."
				echo -e "Please make a dir named '$1' and start the installasion again"
				exit
			fi
		fi
	fi
}

require_dir "bin" "$1"
clear

echo -e "-----------------"
echo -e "Java Installasion"
echo -e "1. Java 17 [Default]"
echo -e "2. Java 20"
javachoice=1
read javachoice

if [[ -z $javachoice ]]; then
  echo -e "Invalid argument, restarting execution..."
  ./javabin
 elif [[ $javachoice == 1 ]]; then
  echo -e "> Executing.."
  echo -e "Installing java 17...."
  rm -rf bin > /dev/null 2>&1
  mkdir /bin > /dev/null 2>&1
  wget -q https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.tar.gz -O java.tar.gz > /dev/null 2>&1
  echo "> Extracting java17.tar.gz"
  tar -xf java.tar.gz
  require_dir "java_bins" "$1"
  mv "jdk-20" java_bins
  rm -rf java.tar.gz
  #cd ..
  #rm -rf bin
fi
